# For the generation of the C statistics the quantitative-style project needs a file with a special formatting. This file generates the required file from the content-style-image-pairs.csv file which can be generated by another script.

import os

content_style_image_pairs_file_url = os.path.join('..', '..', 'data', 'test', 'content-style-image-pairs.csv')
content_style_image_pairs_file = open(content_style_image_pairs_file_url, 'r')

wcs_txt_file = open(os.path.join('..', '..', 'data', 'test', 'wcs.txt'), 'w')

for index, line in enumerate(content_style_image_pairs_file):
    # First line is the header
    if index == 0:
        continue
    _, content_image_filename, style_image_filename = line.strip('\n').split(',')
    content_image_filename_without_ext = os.path.splitext(content_image_filename)[0]
    style_image_filename_without_ext = os.path.splitext(style_image_filename)[0]
    line = ' '.join(['1', content_image_filename_without_ext, style_image_filename_without_ext])
    wcs_txt_file.write(line if index == 1 else f'\n{line}')

content_style_image_pairs_file.close()
wcs_txt_file.close()
